name: authentic_sg_weather
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.1.4
  flutter: 
    sdk: flutter
  location: ^4.3.0
  google_fonts: ^2.1.0
  json_annotation: ^4.0.1
  flutter_spinkit: ^5.0.0

dev_dependencies: 
  build_runner: ^2.0.5
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^1.0.3
  flutter_test: 
    sdk: flutter
  json_serializable: ^4.1.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/wind.png"

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/json/

